FROM node:20-alpine AS builder

ARG SERVICE_NAME
WORKDIR /app

# Copy root workspace and packages
COPY package*.json ./
COPY packages ./packages
COPY services/${SERVICE_NAME} ./services/${SERVICE_NAME}

# Install dependencies and build
RUN npm install
RUN npm --workspace=@linkpulse/common run build
RUN npm --workspace=@linkpulse/events run build
RUN npm --workspace=@linkpulse/logger run build

# If service has prisma schema, generate client
RUN if [ -f "./services/${SERVICE_NAME}/prisma/schema.prisma" ]; then \
      npx prisma generate --schema=./services/${SERVICE_NAME}/prisma/schema.prisma; \
    fi

RUN npm --workspace=@linkpulse/${SERVICE_NAME} run build

EXPOSE 8000 8001 8002 8003 8004 8005 8006 8007 8008

CMD npm --workspace=@linkpulse/${SERVICE_NAME} run start
